### ISSUE TITLE
Crash on dead.

### ISSUE THREAD

**Issue by nlgamerss** [JurassiCraftTeam/JurassiCraft2#301]
[latest.log](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2109312/latest.log)
Server crashes on death,

**Comment by Wyn-Price** [comment]
Are you sure you posted the right crash report? This is a crash for jurassicraft needing LLibrary 1.7.9

**Comment by nlgamerss** [comment]
uh weird, I have 7.12

**Comment by nlgamerss** [comment]
https://gyazo.com/1805c5dd659b4fd0488d6e0f3f92a731

**Comment by nlgamerss** [comment]
Nevermind, I copied my servers log. I think it was in my technic this should be the right one.

**Comment by nlgamerss** [comment]
and here the latest server log : 
[latest (1).log](https://github.com/JurassiCraftTeam/JurassiCraft2/files/2109316/latest.1.log)

**Comment by Wyn-Price** [comment]
Fixed in [96014ad](https://github.com/JurassiCraftTeam/JurassiCraft2/commit/96014adaa0c359f728f6a852a787e2ec1c8fa9de) (1.11), [8b4278f](https://github.com/JurassiCraftTeam/JurassiCraft2/commit/8b4278f395a2a647988204d92ca960e349bf2907) (1.12) and [505f7b8](https://github.com/JurassiCraftTeam/JurassiCraft2/commit/505f7b81b659642e25c5dabfa91fe1d7c83f8a88) (1.13 / revamp)
