### ISSUE TITLE
Major performance lag (over-spawning?)

### ISSUE THREAD

**Issue by Iastre** [JurassiCraftTeam/JurassiCraft2#421]
In trying to put together a server, I have been troubleshooting quite a bit to improve performance. Currently we have an unplayable amount of lag - everything stutters, blocks broken reappear instantly and take a moment to realize they've been broken, and the server sends out a ton of "Can't keep up" messages. And the server's got pretty decent CPU and memory, too.

My collection of mods includes JurassiCraft (2.1.17), which we have been playing with the 'Dinosaur Spawning' option enabled (and 'Allow Carcass Spawning' disabled).

I pulled out JurassiCraft and dropped it on a new server as the only mod (except for LLibrary, of course). The performance was still just as bad, so it does seem to be an issue with JurassiCraft. I also noticed there were quite a lot of dinosaurs spawning (Triceratops in a Mesa biome - I'll attach a screenshot of one of the spots where they seem especially thick). I don't know if the lag is due to uncontrolled spawning, or if the dino code itself needs a bit more optimizing.
![40078962_1836058976483148_1317094615156785152_n](https://user-images.githubusercontent.com/14349072/44631908-ae2d3700-a940-11e8-9e69-b1ebceb9ac70.png)

**Comment by PT400C** [comment]
What do the server's specs look like and did you try using the mod without naturally spawning dinosaurs? What happens then?

**Comment by PT400C** [comment]
I may do some testing too. I've got a pretty similar server at hand. i7-6700K and _enough_ ram. Without naturally spawning dinosaurs I know that it doesn't lag. But I didn't test it with that value enabled yet.

**Comment by EdUb3** [comment]
I am having the same issue with natural spawning, Ryzen7 6 core @3.6GHz. Not only does it lag the server, It also looks very unnatural. Similar to the image posted, I have dinos spawning on top of dinos. Natural spawning off my server will idle at 15%-30% server CPU usage. When I turn natural spawning on it jumps up to a 50%-80% idle. The dinos also move in little spurts, I assume this is due to the CPU overload.

Is there any way to currently reduce the spawn rate of the dinos to fix this? Ive tried setting natural-spawn-rate= to both 75 and 90, this doesn't seem to effect the mod at all. Also tried the "Mob Controller" Forge mod, which promises to be able to control spawn rates of even modded NPCs, and wasn't able to fix it with that either (although that may be user error).

So might there be a value we could set in our .cfg file for the mod itself, to reduce spawn rate? I know by default there isn't, but maybe add a line with {insert-command-from-dev-here}?

**Comment by EdUb3** [comment]
So for anyone that is interested, I found a solution until the spawning is reworked. Two things, first is to set `spawn-animals=false` . This will disable vanilla animal spawning but make will a major mark to CPU usage. With natural spawning on true for JurassiCraft, the dinos will still spawn. Second is to increase your net compression rate on your server, sounds odd but this made a big difference to my CPU usage as well. `network-compression-threshold=512`

Dinos still over spawn, so it still looks unnatural, but the CPU boost will enable them to path correctly, and declump. So things look much better. Server idles at 5%-10% now, with dino spawns on. So Actually even better then before with spawns off.

So when the spawns are reworked, it might be a good idea to decrease vanilla animal spawning as well as the dino spawning.

**Comment by Canus8** [comment]
Is there by chance a way that the natural spawns you accidentally allowed could de-spawn like vanilla mobs such as Llamas, endermen, bats, etc?  Because, I accidentally allowed a lot of them to spawn in, and I can't even go near them now because of how much lag they cause.  I tried to kill off as many as I could with lava, and it would take a minute for the lava to start SPREADING.  With raptors, it was so bad that I could time my retrieval of the lava source with it starting to spread, because that is how long it took for them to take enough lava damage for the fire to eventually kill them.  I want to explore in that direction, but I can't because of the Lagosaurus, Lagoraptors, Lagosaurolophus, and Lagoceratops.  I am also experiencing this on single player, if that means anything.

I don't feel the Mussaurus are much of an issue, though, but against the Raptor lag, I can't tell if they are contributing.

**Comment by PT400C** [comment]
@PT400C Note for me: This is NOT overspawning, the PathFinding AI seems to fail.

**Comment by PT400C** [comment]
@EdUb3 @Iastre This issue should be resolved by the next JC release.
