### ISSUE TITLE
NPE when creating JC dinosaurs before JC postinit

### ISSUE THREAD

**Issue by jredfox** [JurassiCraftTeam/JurassiCraft2#429]
Version:
Issue: evil notch lib in post init goes through all entities and sees whether or not silkspawners can instantiate them later for inside of the world to populate tab arrays. Because without the blacklist of entities not to use for my other mods they would simply crash when rendering and other mods would blame me and not the creator of the broken entity.

Exception:
https://pastebin.com/nnQA0Trx

Solution: could you maybe look for dino foods after they have updated once inside of a tickable world because right now your looking for things that are causing exceptions. **Bbprks core would break and not have your mobs display in your menu either** if instantiation of a fake world fails.

Fake World class to instantiate entities during post init:
https://github.com/jredfox/evilnotchlib/blob/master/src/main/java/com/EvilNotch/lib/minecraft/content/FakeWorld.java

**Comment by CraftedMods** [comment]
The `FoodHelper` will be instantiated in postinit. Addind JC to the dependencies property (a soft dependency) of your mod should fix that, because then the JC postinit function will be invoked before your postinit function.

**Comment by CraftedMods** [comment]
Also, are the mod versions of your mods you're having that issue with available online? Otherwise I cannot do any testing.

**Comment by jredfox** [comment]
no my mod will not be dependent upon yours says it's not an addon could you just simply do it during init where blocks are suppose to be already done?

**Comment by CraftedMods** [comment]
As I said, that would only be a temporary fix. And were're registering our things the right way, the `FoodHelper` just assigns various properties to food items already in the game, and because we may add compatibility for blocks of other blocks, we'll initialize it in postinit.

**Comment by jredfox** [comment]
ok thanks for fixing the issues. I have stuff to do on my side for other mods but, it's related to chunks and lighting and other calls. I am probably going to wind up porting the fake world from bpkrs to 1.12.2 to prevent any further compatability errors that could be prevented on my side.

the render is bigger because I backported the renderer  from 1.7.10 there will be an option for dynamic render 1.10.2+ option disabled by default.

**Comment by CraftedMods** [comment]
Another note: Though this issue is fixed, it doesn't mean that JC and other mods will completely work with silkspawners. You're trying to create entities from mods that are not completely initialized, so chances are always there, that something breaks. The real problem is that you're creating these entities in postinit, for most mods it works, for some maybe not, but it's not bad design of these mod if it doesn't. You're maybe interested into that event: `FMLLoadCompleteEvent`.

**Comment by PT400C** [comment]
@jredfox As it's an issue on your side, I'll close that issue. If you need further support you can still send messages in here.

**Comment by jredfox** [comment]
no this is not an issue on my side is also unable to instantiate jc mobs:
https://minecraft.curseforge.com/projects/menumobs

**Comment by PT400C** [comment]
Tbh, I'm pretty sure that there are many other mods out there making bad practise of displaying the mobs. CraftedMods already pointed out that mods like JEI use a later event to avoid any problems with mods using the postInit event. So, I would suggest changing your code to the `FMLLoadCompleteEvent`. But to assure compatibility with other mods (which won't change their events anymore) we'll probably enhance our system in general.

**Comment by PT400C** [comment]
Well, that's not true at all ;) It was added into Forge in the year 2014.

**Comment by jredfox** [comment]
This cannot be moved to LoadCompleteEvent since it fires after jei and thus the spawners don't populate the tab till after jei's tab and don't show up in the tab. I have to do this in post init for silkspawners

**Comment by CraftedMods** [comment]
@jredfox It seems like you require a very specific loading order. As I said before, this can be managed with the `dependency` propertie of FML. The name is maybe a bit confusing, but this just means that these "dependencies" will be loaded before your mod. I saw many mods which did that, without really depending on these mods. The property could be named `loadAfter`, which probably is more appropriate. The problem with the null check is, as we said before, that this fixes one specific issue for you, but generally, it's likely, that in the future, new issues will arise. And we won't change our internal system completely just because some mods depend on stuff that's not in a stable state internally. I'll discuss that with the team again, because indeed we do care about compatibility, and we've to decide whether we want to support these specific cases, especially if there solutions which work for you, because we're not doing anything wrong. For JEI, eventually the `dependants` property helps you too. As I said before, it's for the loading order, not really to declare specific dependencies.

**Comment by jredfox** [comment]
I don't do anything with the entity besides construct it I don't use any new methods you add. I put you on a whitelist of domains to ignore for living entities and living bases but, still doesn't make it compatible with mob menus.

**Comment by CraftedMods** [comment]
Is your mod processing the JC entities serverside too (I think so)?

**Comment by CraftedMods** [comment]
And menu mobs does indeed blacklist a lot of entities from many popular mods - I think because of the same thing as here - because the entities are initialized in an unstable state.

**Comment by jredfox** [comment]
My FakeWorld#.isRemote is always true

**Comment by PT400C** [comment]
@jredfox Does the issue still exist? If so, please contact me via Discord: PT400C#8363 so that I can be informed about what you talked about in here in detail.
